PASSWORD
harou24/IRC_SERVER pull request #57
Opened 2022-05-11 12:53 UTC by harou24

2022-05-12 12:11 UTC, Eutienne approved these changes
works perfect

2022-05-13 19:19 UTC, Eutienne approved these changes

2022-05-16 16:46 UTC, Eutienne approved these changes

2022-05-16 16:49 UTC, EvitaO requested changes
in the main in irc_server.cpp, can you add a check that the portnbr has to be bigger then 1000 and less then max int? Otherwhise it should give the usage/help messages, with the limits of a port aswell.

2022-05-17 11:33 UTC, EvitaO commented
sorry i checked and max port number is <= 65535, can you change MAX_INT to that number (maybe with a define, so that the definition of that number is clear)

2022-05-17 15:16 UTC, EvitaO approved these changes

2022-05-17 15:26 UTC, merged